### PR TITLE
#256 publishing turned on for the qbeastSpark project

### PR DESCRIPTION
**Pull request by alexeiakimov**
## Description

The change allows to publish snapshot artifacts into local Ivy and Maven repositories.

## Type of change

This an enhancement for development and testing. The production capabilities are not affected.

## Checklist:

Here is the list of things you should do before submitting this pull request:

- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [ ] Add comments to the code (make it easier for the community!).
- [ ] Change the documentation.
- [ ] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

This change does not require automated testing like CI, just manual testing on the developer's machine is enough.

### CODE REVIEW

**Comment by osopardo1** [comment]
Couldn't that change facilitate mistakes in publishing on the Public Maven Repository? Is it possible to add another flag only for local?

**Review by osopardo1 — APPROVED** [review]

**Comment by osopardo1** [comment]
I think this PR should be merged on `main`. Agree?

**Comment by alexeiakimov** [comment]
I am not sure about main, I would suggest to merge to main-1.0.0 and then backport it to main as a separate PR.

**Comment by osopardo1** [comment]
Ok!

**Pull request merged**
